"use client";
import { AppShell } from "@/components/app-shell";
import { DetailDrawer, FilterBar, ReviewFlagBadge } from "@/components/review-ui";
import { MetricCard, StatusBadge } from "@/components/ui";
import { reviewItems } from "@/mocks/review-queue";
import type { ReviewItem } from "@/types/dashboard";
import { useState } from "react";

export function ReviewQueuePage() { const [selected, setSelected] = useState<ReviewItem | null>(null); return <AppShell title="Review queue" description="Flags stay in historical context after resolution. This UI does not modify financial records."><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Open flags" value="3" note="Awaiting a review action" tone="warning" /><MetricCard label="Resolved this month" value="18" note="Retained in queue history" tone="positive" /><MetricCard label="High priority" value="1" note="Possible duplicate payment" tone="danger" /></div><section className="mt-4 border border-line bg-white shadow-card"><div className="flex flex-col justify-between gap-4 border-b border-line px-5 py-4 lg:flex-row lg:items-center"><div><h2 className="font-medium">Flagged records</h2><p className="mt-1 text-sm text-slate-500">Open a record to review its source, related entries, and suggested action.</p></div><FilterBar filters={["Flag type", "Priority", "Status", "Assigned to"]} /></div><ul className="divide-y divide-line">{reviewItems.map((item) => <li key={item.id}><button type="button" className="grid w-full gap-3 px-5 py-4 text-left hover:bg-stone md:grid-cols-[120px_minmax(0,1fr)_110px_130px_100px] md:items-center" onClick={() => setSelected(item)}><ReviewFlagBadge type={item.type} /><span><span className="block text-sm font-medium text-ink">{item.title}</span><span className="mt-1 block text-sm text-slate-500">{item.record} · {item.id}</span></span><span className="text-sm text-slate-500">{item.assignee}</span><span className="text-sm text-slate-500">{item.createdAt}</span><span className="flex gap-2"><StatusBadge status={item.priority} /><StatusBadge status={item.status} /></span></button></li>)}</ul></section>{selected && <DetailDrawer item={selected} onClose={() => setSelected(null)} />}</AppShell>; }
