"use client";

import { motion, useReducedMotion } from "framer-motion";
import { Search, SlidersHorizontal } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { DetailDrawer, ReviewFlagBadge } from "@/components/review-ui";
import { MetricCard, StatusBadge } from "@/components/ui";
import { cardReveal, staggerContainer } from "@/lib/motion";
import { reviewItems } from "@/mocks/review-queue";
import type { ReviewItem } from "@/types/dashboard";
import { useState } from "react";
import { useCanManage } from "@/lib/auth/role-context";

function QueueToolbar() { return <div className="flex min-w-0 flex-wrap items-center gap-2"><label className="relative min-w-[180px] flex-1 sm:flex-none"><Search size={16} className="pointer-events-none absolute left-3 top-3 text-text-muted" /><input aria-label="Search review queue" placeholder="Search flagged records" className="h-11 w-full rounded-md border border-border bg-surface pl-9 pr-3 text-sm text-text-primary placeholder:text-text-muted sm:w-52" /></label>{["Flag type", "Priority", "Status", "Assigned to"].map((label) => <button key={label} type="button" className="inline-flex h-11 items-center rounded-md border border-border bg-surface px-3 text-sm font-medium text-text-secondary hover:bg-surface-muted">{label}</button>)}<button type="button" className="inline-flex h-11 items-center gap-2 rounded-md px-2 text-sm font-medium text-brand-accent hover:bg-surface-accent"><SlidersHorizontal size={16} />More filters</button></div>; }

function ReviewRow({ item, status, onOpen }: { item: ReviewItem; status: ReviewItem["status"]; onOpen: () => void }) { const reducedMotion = useReducedMotion(); return <motion.button variants={reducedMotion ? undefined : cardReveal} initial={reducedMotion ? false : "initial"} animate={reducedMotion ? undefined : "animate"} type="button" onClick={onOpen} className="block w-full min-w-0 px-4 py-4 text-left transition-colors hover:bg-surface-muted/65 sm:px-5 lg:grid lg:grid-cols-[minmax(128px,155px)_minmax(170px,1fr)_minmax(96px,125px)_minmax(90px,110px)_72px_78px] lg:items-center lg:gap-3"><div className="flex min-w-0 items-center justify-between gap-3 lg:block"><div className="min-w-0"><ReviewFlagBadge type={item.type} /></div><div className="shrink-0 lg:hidden"><StatusBadge status={status} /></div></div><div className="mt-3 min-w-0 lg:mt-0"><span className="block truncate text-sm font-semibold text-text-primary">{item.title}</span><span className="mt-1 block truncate text-sm text-text-muted">{item.record} · {item.id}</span></div><div className="mt-3 grid min-w-0 grid-cols-2 gap-3 text-sm lg:contents"><span className="min-w-0 lg:mt-0"><span className="block text-xs text-text-muted lg:hidden">Assigned to</span><span className="block truncate text-text-secondary">{item.assignee}</span></span><span className="min-w-0 lg:mt-0"><span className="block text-xs text-text-muted lg:hidden">Date</span><span className="block truncate text-text-secondary">{item.createdAt}</span></span></div><div className="mt-3 min-w-0 lg:mt-0"><span className="mr-2 text-xs text-text-muted lg:hidden">Priority</span><StatusBadge status={item.priority} /></div><div className="mt-3 hidden min-w-0 lg:block lg:mt-0"><StatusBadge status={status} /></div></motion.button>; }

export function ReviewQueuePage() { const [selected, setSelected] = useState<ReviewItem | null>(null); const [statusById, setStatusById] = useState<Partial<Record<string, ReviewItem["status"]>>>({}); const reducedMotion = useReducedMotion(); const canManage = useCanManage(); const selectedStatus = selected ? statusById[selected.id] ?? selected.status : undefined; return <AppShell title="Review queue" description="Flags stay in historical context after resolution. This UI does not modify financial records."><motion.div variants={reducedMotion ? undefined : staggerContainer} initial={reducedMotion ? false : "initial"} animate={reducedMotion ? undefined : "animate"} className="grid auto-rows-fr gap-4 sm:grid-cols-3">{[{ label: "Open flags", value: "3", note: "Awaiting a review action", tone: "warning" as const }, { label: "Resolved this month", value: "18", note: "Retained in queue history", tone: "positive" as const }, { label: "High priority", value: "1", note: "Possible duplicate payment", tone: "danger" as const }].map((metric) => <MetricCard key={metric.label} {...metric} />)}</motion.div><section className="mt-5 overflow-hidden rounded-card border border-border bg-surface shadow-card"><div className="flex flex-col gap-4 border-b border-border px-5 py-5 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="font-semibold tracking-[-0.01em] text-text-primary">Flagged records</h2><p className="mt-1 text-sm leading-6 text-text-muted">Open a record to review its source, related entries, and suggested action.</p></div><QueueToolbar /></div><ul className="divide-y divide-border">{reviewItems.map((item) => <li key={item.id} className="min-w-0"><ReviewRow item={item} status={statusById[item.id] ?? item.status} onOpen={() => setSelected(item)} /></li>)}</ul></section>{selected && selectedStatus && <DetailDrawer item={{ ...selected, status: selectedStatus }} onClose={() => setSelected(null)} onResolve={canManage ? () => setStatusById((current) => ({ ...current, [selected.id]: "Resolved" })) : undefined} />}</AppShell>; }
