"use client";

import { AppShell } from "@/components/app-shell";
import { ConfirmationDialog, FormField } from "@/components/admin-ui";
import { PrimaryButton, SectionCard } from "@/components/ui";
import { HubSpotSyncControl } from "@/features/admin/hubspot-sync-control";
import { useState } from "react";

const sections = ["Bank transfer entry", "Correct a record", "Product mapping", "Targets", "Summit tracker", "User access", "Integration status"] as const;
type AdminSection = (typeof sections)[number];
const inputClass = "w-full border border-line px-3 py-2";

function AdminForm({ section, onReview }: { section: AdminSection; onReview: () => void }) {
  if (section === "Bank transfer entry") return <><p className="mb-5 text-sm text-slate-500">Creates a future B2C IBAN payment after the same duplicate checks used for processors.</p><div className="grid gap-4 sm:grid-cols-2"><FormField label="Customer email"><input className={inputClass} placeholder="member@example.com" /></FormField><FormField label="Amount (USD)"><input className={inputClass} placeholder="$0" /></FormField><FormField label="Payment date"><input className={inputClass} type="date" /></FormField><FormField label="Category"><select className={inputClass}><option>Membership</option><option>Workshop</option><option>Summit ticket</option></select></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review IBAN entry</PrimaryButton></div></>;
  if (section === "Correct a record") return <><p className="mb-5 text-sm text-slate-500">Every correction will require the authenticated user, before/after values, timestamp, and reason in the audit log.</p><div className="grid gap-4 sm:grid-cols-2"><FormField label="Record"><input defaultValue="B2C transaction · Maya Al Khalifa" className={inputClass} readOnly /></FormField><FormField label="Current value"><input defaultValue="$399" className={inputClass} readOnly /></FormField><FormField label="New value"><input placeholder="Enter corrected value" className={inputClass} /></FormField><FormField label="Reason for change"><input placeholder="Required audit reason" className={inputClass} /></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review correction</PrimaryButton></div></>;
  if (section === "Product mapping") return <><p className="mb-5 text-sm text-slate-500">Map Stripe or Tap products to an approved internal reporting category and membership tier.</p><div className="grid gap-4 sm:grid-cols-3"><FormField label="Processor product"><input className={inputClass} placeholder="Product ID" /></FormField><FormField label="Internal category"><select className={inputClass}><option>Membership</option><option>Workshop</option></select></FormField><FormField label="Membership tier"><select className={inputClass}><option>Premium</option><option>Community</option></select></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review mapping</PrimaryButton></div></>;
  if (section === "Targets") return <><p className="mb-5 text-sm text-slate-500">Annual and quarterly targets are configurable without a code change in the future secure data layer.</p><div className="grid gap-4 sm:grid-cols-3"><FormField label="Target period"><select className={inputClass}><option>Annual 2026</option><option>Q3 2026</option></select></FormField><FormField label="Revenue stream"><select className={inputClass}><option>Total recognised sales</option><option>B2C recognised sales</option><option>B2B recognised sales</option></select></FormField><FormField label="Target (USD)"><input className={inputClass} placeholder="$0" /></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review target</PrimaryButton></div></>;
  if (section === "Summit tracker") return <><p className="mb-5 text-sm text-slate-500">Capture ticket, sponsor, booth, revenue, and cost progress against approved targets.</p><div className="grid gap-4 sm:grid-cols-3"><FormField label="Tracker area"><select className={inputClass}><option>Tickets</option><option>Sponsors</option><option>Booths</option><option>Costs</option></select></FormField><FormField label="New value (USD)"><input className={inputClass} placeholder="$0" /></FormField><FormField label="Reason / source"><input className={inputClass} placeholder="Approved source note" /></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review Summit update</PrimaryButton></div></>;
  if (section === "Integration status") return <HubSpotSyncControl />;
  return <div className="border border-line bg-stone p-6"><p className="font-medium text-ink">{section}</p><p className="mt-2 text-sm text-slate-600">This area is intentionally a visible placeholder. Live access control and integration health require their respective secure backend phases.</p></div>;
}

export function AdminPage() { const [active, setActive] = useState<AdminSection>("Correct a record"); const [confirming, setConfirming] = useState(false); return <AppShell title="Admin" description="Controlled finance administration UI. No form writes are enabled until the secure backend phase."><div className="grid gap-4 lg:grid-cols-[220px_minmax(0,1fr)]"><SectionCard title="Admin sections"><nav aria-label="Admin sections" className="space-y-1">{sections.map((section) => <button key={section} type="button" onClick={() => setActive(section)} className={`block w-full px-3 py-2 text-left text-sm ${active === section ? "bg-mint text-forest" : "text-slate-600 hover:bg-stone"}`}>{section}{(section === "User access" || section === "Integration status") && <span className="float-right text-xs text-slate-400">Placeholder</span>}</button>)}</nav></SectionCard><SectionCard title={active} description="UI preview only; server-side authorization, validation, audit logging, and saving are intentionally not implemented."><AdminForm section={active} onReview={() => setConfirming(true)} /></SectionCard></div>{confirming && <ConfirmationDialog title="Confirm admin change" description="This is a UI-only preview. Saving is unavailable until server-side authorization and audit recording are implemented." onClose={() => setConfirming(false)} />}</AppShell>; }
