"use client";

import { ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ConfirmationDialog, FormField } from "@/components/admin-ui";
import { PrimaryButton, SectionCard } from "@/components/ui";
import { HubSpotSyncControl } from "@/features/admin/hubspot-sync-control";
import { HubSpotDuplicateReview } from "@/features/admin/hubspot-duplicate-review";
import { HubSpotBackfillControl } from "@/features/admin/hubspot-backfill-control";
import { StripeSyncControl } from "@/features/admin/stripe-sync-control";
import { StripeBackfillControl } from "@/features/admin/stripe-backfill-control";
import { TapSyncControl } from "@/features/admin/tap-sync-control";
import { TapBackfillControl } from "@/features/admin/tap-backfill-control";
import { IntegrationRunSummary } from "@/features/admin/integration-run-summary";
import { useState } from "react";

const sections = ["Bank transfer entry", "Correct a record", "Product mapping", "Targets", "Summit tracker", "User access", "Integration status"] as const;
type AdminSection = (typeof sections)[number];
const inputClass = "h-10 w-full rounded-md border border-border bg-surface px-3 text-sm text-text-primary placeholder:text-text-muted";

function AdminForm({ section, onReview, refreshToken, onRunSettled }: { section: AdminSection; onReview: () => void; refreshToken: number; onRunSettled: () => void }) {
  if (section === "Bank transfer entry") return <><p className="mb-5 text-sm leading-6 text-text-muted">Creates a future B2C IBAN payment after the same duplicate checks used for processors.</p><div className="grid gap-4 sm:grid-cols-2"><FormField label="Customer email"><input className={inputClass} placeholder="member@example.com" /></FormField><FormField label="Amount (USD)"><input className={inputClass} placeholder="$0" /></FormField><FormField label="Payment date"><input className={inputClass} type="date" /></FormField><FormField label="Category"><select className={inputClass}><option>Membership</option><option>Workshop</option><option>Summit ticket</option></select></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review IBAN entry</PrimaryButton></div></>;
  if (section === "Correct a record") return <><p className="mb-5 text-sm leading-6 text-text-muted">Every correction requires the authenticated user, before/after values, timestamp, and reason in the audit log.</p><div className="grid gap-4 sm:grid-cols-2"><FormField label="Record"><input defaultValue="B2C transaction · Maya Al Khalifa" className={`${inputClass} bg-surface-muted`} readOnly /></FormField><FormField label="Current value"><input defaultValue="$399" className={`${inputClass} bg-surface-muted`} readOnly /></FormField><FormField label="New value"><input placeholder="Enter corrected value" className={inputClass} /></FormField><FormField label="Reason for change"><input placeholder="Required audit reason" className={inputClass} /></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review correction</PrimaryButton></div></>;
  if (section === "Product mapping") return <><p className="mb-5 text-sm leading-6 text-text-muted">Map Stripe or Tap products to an approved internal reporting category and membership tier.</p><div className="grid gap-4 sm:grid-cols-3"><FormField label="Processor product"><input className={inputClass} placeholder="Product ID" /></FormField><FormField label="Internal category"><select className={inputClass}><option>Membership</option><option>Workshop</option></select></FormField><FormField label="Membership tier"><select className={inputClass}><option>Premium</option><option>Community</option></select></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review mapping</PrimaryButton></div></>;
  if (section === "Targets") return <><p className="mb-5 text-sm leading-6 text-text-muted">Annual and quarterly targets are configurable without a code change in the future secure data layer.</p><div className="grid gap-4 sm:grid-cols-3"><FormField label="Target period"><select className={inputClass}><option>Annual 2026</option><option>Q3 2026</option></select></FormField><FormField label="Revenue stream"><select className={inputClass}><option>Total recognised sales</option><option>B2C recognised sales</option><option>B2B recognised sales</option></select></FormField><FormField label="Target (USD)"><input className={inputClass} placeholder="$0" /></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review target</PrimaryButton></div></>;
  if (section === "Summit tracker") return <><p className="mb-5 text-sm leading-6 text-text-muted">Capture ticket, sponsor, booth, revenue, and cost progress against approved targets.</p><div className="grid gap-4 sm:grid-cols-3"><FormField label="Tracker area"><select className={inputClass}><option>Tickets</option><option>Sponsors</option><option>Booths</option><option>Costs</option></select></FormField><FormField label="New value (USD)"><input className={inputClass} placeholder="$0" /></FormField><FormField label="Reason / source"><input className={inputClass} placeholder="Approved source note" /></FormField></div><div className="mt-5"><PrimaryButton onClick={onReview}>Review Summit update</PrimaryButton></div></>;
  if (section === "Integration status") return <><IntegrationRunSummary refreshToken={refreshToken} /><StripeSyncControl /><div className="mt-4"><StripeBackfillControl onRunSettled={onRunSettled} /></div><div className="mt-4"><TapSyncControl /></div><div className="mt-4"><TapBackfillControl onRunSettled={onRunSettled} /></div><div className="mt-4"><HubSpotSyncControl /></div><div className="mt-4"><HubSpotBackfillControl onRunSettled={onRunSettled} /></div><HubSpotDuplicateReview /></>;
  return <div className="rounded-md border border-border bg-surface-muted/70 p-5"><p className="font-medium text-text-primary">{section}</p><p className="mt-2 text-sm leading-6 text-text-muted">This area is intentionally a visible placeholder. Live access control and integration health require their respective secure backend phases.</p></div>;
}

export function AdminPage() { const [active, setActive] = useState<AdminSection>("Correct a record"); const [confirming, setConfirming] = useState(false); const [backfillRefreshToken, setBackfillRefreshToken] = useState(0); const isLiveIntegration = active === "Integration status"; return <AppShell title="Administration" description="Controlled finance administration. Reconciliation, backfill, and duplicate decisions are server-authorized and audited; source-deal corrections happen in B2B Operations."><div className="mb-4 flex items-center gap-3 rounded-card border border-brand-accent/15 bg-surface-accent/55 px-4 py-3"><ShieldCheck size={18} className="shrink-0 text-brand-accent" /><p className="text-sm leading-6 text-text-secondary">Administrative controls are intentionally separate from operational reporting. Important financial changes remain attributable and auditable.</p></div><div className="grid gap-4 lg:grid-cols-[238px_minmax(0,1fr)]"><SectionCard title="Administration"><nav aria-label="Admin sections" className="space-y-1">{sections.map((section) => <button key={section} type="button" onClick={() => setActive(section)} className={`flex w-full items-center justify-between rounded-md px-3 py-2.5 text-left text-sm font-medium transition-colors ${active === section ? "bg-brand-primary text-white shadow-sm" : "text-text-secondary hover:bg-surface-muted hover:text-text-primary"}`}><span>{section}</span>{section === "User access" && <span className={`text-[10px] font-semibold uppercase tracking-wide ${active === section ? "text-white/60" : "text-text-muted"}`}>Preview</span>}</button>)}</nav></SectionCard><SectionCard title={active} description={isLiveIntegration ? "Admin-only HubSpot reconciliation, historical backfill, and duplicate decisions. Source-deal corrections happen in B2B Operations and are audited there." : "UI preview only; server-side authorization, validation, audit logging, and saving are intentionally not implemented."}><AdminForm section={active} onReview={() => setConfirming(true)} refreshToken={backfillRefreshToken} onRunSettled={() => setBackfillRefreshToken((value) => value + 1)} /></SectionCard></div>{confirming && <ConfirmationDialog title="Confirm admin change" description="This is a UI-only preview. Saving is unavailable until server-side authorization and audit recording are implemented." onClose={() => setConfirming(false)} />}</AppShell>; }
