import { BreakdownChart } from "@/components/charts";
import { AppShell } from "@/components/app-shell";
import { DataTable, DateRangeSelector, FilterBar, MetricCard, NotBackfilledState, ProgressMetric, SectionCard, StatusBadge, TableCell, TableHead, TableHeader } from "@/components/ui";
import { expenseBreakdown, financeMetrics, financialEntries, summitMetrics } from "@/mocks/finance";

export function FinanceOverview() { return <AppShell title="Finance" description="A controlled view of cash, recognised revenue, expenses, and Summit performance. B2B bookings remain separate from recognised sales." controls={<DateRangeSelector />}>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{financeMetrics.map((metric, index) => <MetricCard key={metric.label} {...metric} emphasis={index === 0} />)}</div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(340px,0.8fr)]">
    <SectionCard title="Expense breakdown" description="Approved and paid expenses for the selected period"><BreakdownChart data={expenseBreakdown} /></SectionCard>
    <SectionCard title="Revenue separation" description="These concepts must never be added together as the same measure"><dl className="divide-y divide-border"><div className="flex items-center justify-between gap-4 py-4 first:pt-0"><dt className="text-sm text-text-secondary">B2C recognised sales</dt><dd className="font-semibold tabular-nums text-text-primary">$96,800</dd></div><div className="flex items-center justify-between gap-4 py-4"><dt className="text-sm text-text-secondary">B2B recognised sales</dt><dd className="font-semibold tabular-nums text-text-primary">$87,400</dd></div><div className="flex items-center justify-between gap-4 py-4 last:pb-0"><dt className="text-sm text-text-secondary">B2B bookings</dt><dd className="font-semibold tabular-nums text-brand-accent">$126,000</dd></div></dl><p className="mt-5 rounded-md bg-surface-muted px-3 py-2.5 text-xs leading-5 text-text-muted">Bookings are commitments; they are not recognised sales or cash received.</p></SectionCard>
  </div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.3fr)_minmax(340px,1fr)]"><SectionCard title="Summit progress" description="Targets are illustrative until approved Finance sources are connected"><div className="grid gap-6 sm:grid-cols-2">{summitMetrics.map((metric) => <ProgressMetric key={metric.label} {...metric} />)}</div></SectionCard><NotBackfilledState title="Cash trend not loaded" description="No historical cash series is available in the UI foundation. It must not be displayed as $0." /></div>
  <SectionCard title="Financial entries" description="Illustrative ledger rows preserve the distinction between bookings, recognised sales, and expenses." action={<FilterBar filters={["Date", "Area", "Status"]} />} className="mt-4"><DataTable caption="Financial entries"><TableHead><TableHeader>Date</TableHeader><TableHeader>Description</TableHeader><TableHeader>Area</TableHeader><TableHeader>Amount</TableHeader><TableHeader>Status</TableHeader></TableHead><tbody className="divide-y divide-border">{financialEntries.map((entry) => <tr key={entry.description}><TableCell>{entry.date}</TableCell><TableCell className="font-medium text-text-primary">{entry.description}</TableCell><TableCell>{entry.area}</TableCell><TableCell className="font-medium tabular-nums text-text-primary">{entry.amount}</TableCell><TableCell><StatusBadge status={entry.status} /></TableCell></tr>)}</tbody></DataTable></SectionCard>
</AppShell>; }
