"use client";

import { Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { TrendPoint } from "@/types/dashboard";

const chart = { b2c: "rgb(var(--color-chart-b2c))", b2b: "rgb(var(--color-chart-b2b))", bookings: "rgb(var(--color-chart-bookings))", pipeline: "rgb(var(--color-chart-pipeline))", other: "rgb(var(--color-chart-other))", text: "rgb(var(--color-text-muted))", border: "rgb(var(--color-border))", surface: "rgb(var(--color-surface))" };
const breakdownColors = [chart.b2c, chart.b2b, chart.bookings, chart.pipeline, chart.other];
const tooltipStyle = { borderRadius: "var(--radius-sm)", border: "1px solid rgb(var(--color-border))", boxShadow: "var(--shadow-card)", background: chart.surface, color: "rgb(var(--color-text-primary))", fontSize: 12 };

export function SalesTrendChart({ data }: { data: TrendPoint[] }) { return <div className="h-56 sm:h-64" role="img" aria-label="Six-month sales trend showing separately labelled B2C recognised sales, B2B recognised sales, and other sales"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 8, right: 8, left: -10, bottom: 0 }}><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: chart.text, fontSize: 12 }} /><YAxis tickFormatter={(value: number) => `$${value / 1000}k`} tickLine={false} axisLine={false} tick={{ fill: chart.text, fontSize: 12 }} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [`$${value.toLocaleString()}`, ""]} cursor={{ stroke: chart.border }} /><Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 12, color: chart.text, paddingTop: 8 }} /><Line type="monotone" dataKey="b2c" name="B2C recognised" stroke={chart.b2c} strokeWidth={2.25} dot={false} activeDot={{ r: 4 }} /><Line type="monotone" dataKey="b2b" name="B2B recognised" stroke={chart.b2b} strokeWidth={2.25} dot={false} activeDot={{ r: 4 }} /><Line type="monotone" dataKey="other" name="Other" stroke={chart.other} strokeWidth={2} dot={false} activeDot={{ r: 4 }} /></LineChart></ResponsiveContainer></div>; }
export function BreakdownChart({ data }: { data: Array<{ name: string; value: number }> }) { return <div className="h-48 sm:h-52" role="img" aria-label={`Breakdown chart: ${data.map((item) => `${item.name} ${item.value}`).join(", ")}`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={48} outerRadius={74} paddingAngle={3} stroke="none">{data.map((entry, index) => <Cell key={entry.name} fill={breakdownColors[index % breakdownColors.length]} />)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => value > 1000 ? `$${value.toLocaleString()}` : `${value}%`} /><Legend verticalAlign="bottom" iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 12, color: chart.text }} /></PieChart></ResponsiveContainer></div>; }
