"use client";

import { motion, useReducedMotion } from "framer-motion";
import { AlertTriangle, CheckCircle2, ChevronDown, CircleAlert, Clock3, Loader2, Search, SlidersHorizontal } from "lucide-react";
import type { ReactNode } from "react";
import { formatUsd } from "@/lib/format";
import { cardReveal, motionTransition, sectionReveal } from "@/lib/motion";
import type { MetricTone, RecordStatus, ReviewFlag } from "@/types/dashboard";

const statusStyles: Record<string, { style: string; icon?: typeof CheckCircle2 }> = {
  Completed: { style: "bg-success/10 text-success ring-success/20", icon: CheckCircle2 }, Open: { style: "bg-warning/10 text-warning ring-warning/20", icon: Clock3 }, Pending: { style: "bg-brand-accent/10 text-brand-accent ring-brand-accent/20", icon: Clock3 }, Processing: { style: "bg-brand-accent/10 text-brand-accent ring-brand-accent/20", icon: Loader2 }, Failed: { style: "bg-danger/10 text-danger ring-danger/20", icon: CircleAlert }, Refunded: { style: "bg-brand-accent/10 text-brand-accent ring-brand-accent/20" }, Resolved: { style: "bg-surface-muted text-text-secondary ring-border", icon: CheckCircle2 }, "Not loaded": { style: "bg-surface-muted text-text-muted ring-border", icon: AlertTriangle }, "Possible duplicate": { style: "bg-warning/10 text-warning ring-warning/20", icon: AlertTriangle }, "Needs financial details": { style: "bg-danger/10 text-danger ring-danger/20", icon: CircleAlert }, "Needs close date": { style: "bg-danger/10 text-danger ring-danger/20", icon: CircleAlert }, "Missing customer email": { style: "bg-danger/10 text-danger ring-danger/20", icon: CircleAlert }, "Unmapped product": { style: "bg-warning/10 text-warning ring-warning/20" }, "Needs follow-up": { style: "bg-brand-accent/10 text-brand-accent ring-brand-accent/20" }, "Ahead of target": { style: "bg-success/10 text-success ring-success/20", icon: CheckCircle2 }, "Behind target": { style: "bg-danger/10 text-danger ring-danger/20", icon: CircleAlert },
};

export function StatusBadge({ status }: { status: RecordStatus | ReviewFlag | string }) { const config = statusStyles[status] ?? { style: "bg-surface-muted text-text-secondary ring-border" }; const Icon = config.icon; return <span className={`inline-flex whitespace-nowrap items-center gap-1.5 rounded-pill px-2.5 py-1 text-xs font-medium ring-1 ring-inset ${config.style}`}>{Icon && <Icon size={12} aria-hidden="true" className={status === "Processing" ? "animate-spin" : ""} />}{status}</span>; }

export function SectionCard({ title, description, action, children, className = "" }: { title?: string; description?: string; action?: ReactNode; children: ReactNode; className?: string }) { const reducedMotion = useReducedMotion(); return <motion.section variants={reducedMotion ? undefined : sectionReveal} initial={reducedMotion ? false : "initial"} animate={reducedMotion ? undefined : "animate"} className={`overflow-hidden rounded-card border border-border bg-surface shadow-card ${className}`}>{(title || action) && <div className="flex flex-col gap-3 border-b border-border px-5 py-4 sm:flex-row sm:items-start sm:justify-between"><div>{title && <h2 className="text-base font-semibold tracking-[-0.02em] text-text-primary">{title}</h2>}{description && <p className="mt-1 max-w-3xl text-sm leading-6 text-text-muted">{description}</p>}</div>{action && <div className="shrink-0">{action}</div>}</div>}<div className="p-5">{children}</div></motion.section>; }

export function MetricCard({ label, value, note, tone = "neutral", emphasis = false }: { label: string; value: number | string | null; note: string; tone?: MetricTone; emphasis?: boolean }) { const reducedMotion = useReducedMotion(); const toneClass = { positive: "text-success", neutral: "text-text-muted", warning: "text-warning", danger: "text-danger" }[tone]; return <motion.article variants={reducedMotion ? undefined : cardReveal} initial={reducedMotion ? false : "initial"} animate={reducedMotion ? undefined : "animate"} className={`relative overflow-hidden rounded-card border p-5 shadow-card ${emphasis ? "border-brand-primary bg-brand-primary text-white" : "border-border bg-surface"}`}><span aria-hidden="true" className={`absolute inset-x-0 top-0 h-0.5 ${emphasis ? "bg-brand-lime" : tone === "positive" ? "bg-success" : tone === "warning" ? "bg-warning" : tone === "danger" ? "bg-danger" : "bg-brand-accent/55"}`} /><p className={`text-sm ${emphasis ? "text-white/65" : "text-text-muted"}`}>{label}</p><p className={`mt-2 font-medium tracking-[-0.045em] tabular-nums ${emphasis ? "text-3xl text-white" : "text-2xl text-text-primary"}`}>{typeof value === "number" ? formatUsd(value) : value ?? "—"}</p><p className={`mt-2 text-xs leading-5 ${emphasis ? "text-brand-lime" : toneClass}`}>{note}</p></motion.article>; }

export function ProgressMetric({ label, value, target, progress }: { label: string; value: string; target: string; progress: number }) { return <div><div className="flex items-baseline justify-between gap-2"><span className="text-sm font-medium text-text-secondary">{label}</span><span className="text-sm font-semibold tabular-nums text-text-primary">{value}</span></div><div className="mt-2 h-2 overflow-hidden rounded-pill bg-surface-muted" role="progressbar" aria-label={`${label} progress`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><div className="h-full rounded-pill bg-brand-accent" style={{ width: `${progress}%` }} /></div><p className="mt-1.5 text-xs text-text-muted">Target {target} · {progress}%</p></div>; }

export function DateRangeSelector() { return <motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.98 }} transition={motionTransition} type="button" className="inline-flex items-center gap-2 rounded-pill border border-border bg-surface px-3.5 py-2 text-sm font-medium text-text-secondary shadow-card hover:border-brand-accent/30 hover:text-text-primary" aria-label="Select reporting date range">1–31 August 2026 <ChevronDown size={15} /></motion.button>; }

export function FilterBar({ filters = ["Date", "Status"] }: { filters?: string[] }) { return <div className="flex flex-wrap items-center gap-2"><label className="relative"><Search size={16} className="pointer-events-none absolute left-3 top-2.5 text-text-muted" /><input aria-label="Search records" placeholder="Search records" className="h-9 rounded-pill border border-border bg-surface pl-9 pr-3 text-sm text-text-primary placeholder:text-text-muted focus:border-brand-accent" /></label>{filters.map((filter) => <motion.button whileHover={{ y: -1 }} whileTap={{ scale: 0.98 }} transition={motionTransition} key={filter} type="button" className="inline-flex h-9 items-center gap-2 rounded-pill border border-border bg-surface px-3 text-sm text-text-secondary hover:border-brand-accent/30 hover:text-text-primary">{filter}<ChevronDown size={14} /></motion.button>)}<button type="button" className="inline-flex h-9 items-center gap-2 rounded-pill px-2 text-sm font-medium text-brand-accent hover:bg-surface-accent"><SlidersHorizontal size={15} />More filters</button></div>; }

export function DataTable({ children, caption }: { children: ReactNode; caption: string }) { return <div className="overflow-x-auto"><table className="min-w-full text-left text-sm [&_tbody>tr]:transition-colors [&_tbody>tr:hover]:bg-surface-muted/65"><caption className="sr-only">{caption}</caption>{children}</table></div>; }
export function TableHead({ children }: { children: ReactNode }) { return <thead className="border-y border-border bg-surface-muted/80 text-[11px] font-semibold uppercase tracking-[0.08em] text-text-muted"><tr>{children}</tr></thead>; }
export function TableHeader({ children }: { children: ReactNode }) { return <th scope="col" className="whitespace-nowrap px-4 py-3.5 font-semibold">{children}</th>; }
export function TableCell({ children, className = "" }: { children: ReactNode; className?: string }) { return <td className={`whitespace-nowrap px-4 py-3.5 align-top text-text-secondary ${className}`}>{children}</td>; }

export function LoadingSkeleton({ rows = 3 }: { rows?: number }) { return <div aria-label="Loading data" className="space-y-3">{Array.from({ length: rows }, (_, index) => <div key={index} className="h-5 w-full animate-pulse rounded-sm bg-surface-muted" />)}</div>; }
export function EmptyState({ title = "No records yet", description = "Records will appear here when they are available." }: { title?: string; description?: string }) { return <div className="py-10 text-center"><p className="font-semibold text-text-primary">{title}</p><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-text-muted">{description}</p></div>; }
export function ErrorState({ title = "Unable to load this section", description = "Please try again. If the issue continues, contact the finance team." }: { title?: string; description?: string }) { return <div role="alert" className="flex gap-3 rounded-card border border-danger/20 bg-danger/5 p-4 text-danger"><CircleAlert className="shrink-0" size={18} /><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm">{description}</p></div></div>; }
export function NotBackfilledState({ title = "Historical data not available", description = "This period has not yet been backfilled. It is intentionally not shown as zero." }: { title?: string; description?: string }) { return <div className="flex gap-3 rounded-card border border-border bg-surface-muted/70 p-4"><AlertTriangle className="shrink-0 text-warning" size={18} /><div><p className="font-semibold text-text-primary">{title}</p><p className="mt-1 text-sm leading-6 text-text-muted">{description}</p></div></div>; }
export function PermissionRestrictedState() { return <div className="rounded-card border border-border bg-surface-muted p-6 text-center"><p className="font-semibold text-text-primary">Access restricted</p><p className="mt-1 text-sm text-text-muted">Your role does not include access to this area.</p></div>; }
export function PrimaryButton({ children, onClick, disabled = false, type = "button" }: { children: ReactNode; onClick?: () => void; disabled?: boolean; type?: "button" | "submit" }) { return <motion.button whileHover={disabled ? undefined : { y: -1 }} whileTap={disabled ? undefined : { scale: 0.98 }} transition={motionTransition} type={type} onClick={onClick} disabled={disabled} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-pill bg-brand-lime px-4 py-2 text-sm font-semibold text-brand-primary shadow-cta transition-colors hover:bg-brand-lime-hover disabled:cursor-not-allowed disabled:opacity-60">{children}</motion.button>; }
export function SubtleLoading() { return <span className="inline-flex items-center gap-2 text-sm text-text-muted"><Loader2 size={15} className="animate-spin" />Loading</span>; }
