import type { DatabaseClient } from "@/lib/supabase/server";
import { createFinanceSourceIdentity } from "@/lib/b2c/finance-source-identity";
import type { FinanceImportRequestInput } from "@/lib/validation/b2c-finance-import-contracts";
import { normalizeText, type FinanceImportAssessment } from "@/server/services/b2c-finance-reconciliation";
import type {
  FinanceImportRowMatch,
  FinanceImportVersionPreviousRow,
  FinanceImportVersionRepresentedPayment,
  PersistableFinanceImportCandidate,
} from "@/server/services/b2c-finance-import-versioning";
import type { Json } from "@/types/database.generated";

export type B2cReconciliationSafeSummary = {
  publicationState: "not_fully_loaded";
  publicationMessage: string;
  sources: Array<{ key: "payment_tracker" | "tap_statement" | "stripe_charges"; label: string; status: "pending" | "processing" | "completed" | "failed" | "not_loaded" }>;
  counts: { stagedRows: number; validRows: number; needsReviewRows: number; zeroValueRows: number; invalidRows: number; unresolvedGroups: number };
};

export type FinanceImportVersionState = {
  previous: FinanceImportVersionPreviousRow[];
  representedPayments: FinanceImportVersionRepresentedPayment[];
};

export class SupabaseB2cFinanceReconciliationRepository {
  constructor(private readonly client: DatabaseClient) {}

  /**
   * Reads the prior completed Payment Tracker import's lineaged rows (for the
   * version diff) and every payment identity already reserved by a manual bank
   * transfer, regardless of whether a prior import is being superseded.
   */
  async getPaymentTrackerVersionState(supersedesImportId: string | null): Promise<FinanceImportVersionState> {
    const [previous, representedPayments] = await Promise.all([
      supersedesImportId ? this.getPreviousImportLineagedRows(supersedesImportId) : Promise.resolve([]),
      this.getRepresentedPaymentLineages(),
    ]);
    return { previous, representedPayments };
  }

  private async getPreviousImportLineagedRows(importId: string): Promise<FinanceImportVersionPreviousRow[]> {
    const { data: rows, error } = await this.client
      .from("b2c_finance_staging_rows")
      .select("id,normalized_customer_name,occurred_on,amount_usd,payment_method_raw")
      .eq("import_id", importId);
    if (error) throw new Error("Could not load the superseded B2C Finance import rows.");
    if (!rows || rows.length === 0) return [];

    const { data: links, error: linksError } = await this.client
      .from("b2c_finance_row_lineage_links")
      .select("finance_row_id,lineage_id")
      .in("finance_row_id", rows.map((row) => row.id));
    if (linksError) throw new Error("Could not load the superseded B2C Finance import lineage links.");

    const lineageIdByRowId = new Map((links ?? []).map((link) => [link.finance_row_id, link.lineage_id]));

    // A staging row with no lineage link was never confirmed; it cannot be "previous" for diff purposes.
    return rows.flatMap((row) => {
      const lineageId = lineageIdByRowId.get(row.id);
      const normalizedPaymentMethod = normalizeText(row.payment_method_raw);
      if (!lineageId || !row.normalized_customer_name || !row.occurred_on || !row.amount_usd || !normalizedPaymentMethod) return [];
      return [{
        financeRowId: row.id,
        lineageId,
        sourceIdentity: createFinanceSourceIdentity({
          normalizedCustomerName: row.normalized_customer_name,
          occurredOn: row.occurred_on,
          amountUsd: row.amount_usd,
          normalizedPaymentMethod,
        }),
      }];
    });
  }

  /** The stored `source_identity` is authoritative: it is the identity the database trigger reserved at insert time. */
  private async getRepresentedPaymentLineages(): Promise<FinanceImportVersionRepresentedPayment[]> {
    const { data, error } = await this.client
      .from("b2c_finance_record_lineages")
      .select("id,source_identity,represented_payment_id")
      .not("represented_payment_id", "is", null);
    if (error) throw new Error("Could not load B2C Finance represented payment lineages.");

    return (data ?? []).flatMap((lineage) => (lineage.represented_payment_id
      ? [{ paymentId: lineage.represented_payment_id, lineageId: lineage.id, sourceIdentity: lineage.source_identity }]
      : []));
  }

  /**
   * The SQL function persists the import, every staged row, the unchanged-row
   * lineage links, and the remaining safe version-diff candidates in one
   * transaction. `rowIds` are pre-generated by the caller so the same ids used
   * to compute the version diff are the ids inserted as staging rows.
   */
  async finalizeFinanceImportVersion(
    input: FinanceImportRequestInput,
    assessment: FinanceImportAssessment,
    rowIds: string[],
    version: { supersedesImportId: string | null; unchanged: FinanceImportRowMatch[]; candidates: PersistableFinanceImportCandidate[] },
  ): Promise<string> {
    const sourceRows = input.rows.map((row, index) => {
      const assessed = assessment.rows[index];
      return {
        id: rowIds[index],
        sourceTab: row.sourceTab,
        sourceRowNumber: row.sourceRowNumber,
        rawPayload: row.rawPayload as Json,
        reportedDateRaw: row.reportedDateRaw,
        declaredMonthRaw: row.declaredMonth ?? null,
        declaredYearRaw: row.declaredYear ?? null,
        amountUsdRaw: row.amountUsdRaw ?? null,
        customerNameRaw: row.customerNameRaw ?? null,
        customerEmailRaw: row.customerEmailRaw ?? null,
        customerPhoneRaw: row.customerPhoneRaw ?? null,
        categoryRaw: row.categoryRaw ?? null,
        membershipTypeRaw: row.membershipTypeRaw ?? null,
        paymentMethodRaw: row.paymentMethodRaw ?? null,
        paymentStatusRaw: row.paymentStatusRaw ?? null,
        noteRaw: row.noteRaw ?? null,
        occurredOn: assessed.occurredOn,
        amountUsd: assessed.amountUsd,
        normalizedCustomerName: assessed.normalizedCustomerName,
        normalizedCustomerEmail: assessed.normalizedCustomerEmail,
        normalizedCustomerPhone: assessed.normalizedCustomerPhone,
        rowQuality: assessed.quality,
        qualityIssues: assessed.issues,
      };
    });
    const { data, error } = await this.client.rpc("finalize_b2c_finance_import_version", {
      p_source_file_name: input.sourceFileName,
      p_source_file_sha256: input.sourceFileSha256,
      p_source_storage_bucket: input.sourceStorageBucket,
      p_source_storage_path: input.sourceStoragePath,
      p_supersedes_import_id: version.supersedesImportId,
      p_rows: sourceRows,
      p_unchanged: version.unchanged.map((match) => ({ financeRowId: match.financeRowId, lineageId: match.lineageId })),
      p_candidates: version.candidates.map((candidate) => ({
        candidateKind: candidate.candidateKind,
        sourceIdentity: candidate.sourceIdentity,
        financeRowIds: candidate.financeRowIds,
        priorLineageIds: candidate.priorLineageIds,
        priorPaymentIds: candidate.priorPaymentIds,
      })),
    });
    if (error || !data) throw new Error("Could not finalize the B2C Finance import.");
    return data;
  }

  async getSafeSummary(): Promise<B2cReconciliationSafeSummary> {
    const { data, error } = await this.client.rpc("get_b2c_reconciliation_safe_summary", {});
    if (error || !data || typeof data !== "object" || Array.isArray(data)) throw new Error("Could not load the B2C reconciliation summary.");
    return data as B2cReconciliationSafeSummary;
  }
}
